image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
environment:
  site: melmon.dev
tasks:
- package_http: |
    cd $site
    cd http
    tar -cvz . > ../../httpsite.tar.gz
- upload_http: |
    hut pages publish --not-found ./404.html -d $site httpsite.tar.gz
#- package_gemini: |
#    cd $site
#    cd gemini
#    tar -cvz . > ../../geminisite.tar.gz
#- upload_gemini: |
#    acurl -f https://pages.sr.ht/publish/$site \
#        -Fcontent=@geminisite.tar.gz \
#        -Fprotocol=GEMINI
